<?php

namespace TestBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMostPopularArticles()
    {
        return $this->createQueryBuilder('article')
            ->select('article')
            ->orderBy('article.nbrvue', 'DESC')
            ->getQuery()
            ->execute();

    }


public function FindArticleByTags($nom)
{
    $query=$this->getEntityManager()
        ->createQuery("Select m From TestBundle:Article m 
                Where m.idtag in (SELECT t.idtag FROM TestBundle:Tags t where t.nomtag LIKE '$nom')");
    return $query->getResult();
}


    public function FindAjax($nom){
        $query=$this->getEntityManager()->createQuery("Select p from TestBundle:Article p 
                    WHERE p.nomart LIKE :nom")->setParameter("nomart","%".$nom."%");
        return $query->getResult();
    }

}
