<?php

namespace TestBundle\Repository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieWSRepository extends \Doctrine\ORM\EntityRepository
{

    public function FindByNom($nom)
    {
        $query=$this->getEntityManager()
                     ->createQuery("SELECT a from TestBundle:Categoriews a where a.nomcws LIKE '$nom%' ");

                      return $query->getResult();
    }



}
