<?php

namespace TestBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByiduser($id)
    {
        $query=$this->getEntityManager()->createQuery("select e from TestBundle:Evenement e WHERE e.iduser='$id' ");
        return $query->getResult();
    }

    public function findByetatev($etat)
    {
        $query=$this->getEntityManager()->createQuery("select e from TestBundle:Evenement e WHERE e.etatev=1 ");
        return $query->getResult();
    }

    public function updateEtat($date)
    {
        $query = $this->getEntityManager()->createQuery("update TestBundle:Evenement e set e.etatev =-1 where e.datefin<'$date'");
        $query->execute();
    }

    public function updateNbPartitipation($id)
    {
        $query = $this->getEntityManager()->createQuery("update TestBundle:Evenement e set e.nbrparticipants =e.nbrparticipants-1 where e.idev='$id'");
        $query->execute();
    }
}
