<?php

namespace TestBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{
    public function NbFavParCat(){
        $query=$this->getEntityManager()
            ->createQuery("Select  c.nomcp as catnom , COUNT(f)as nbfav from TestBundle:Categorieprod c ,TestBundle:Favoris f WHERE c.idcp=f.idcp GROUP BY c.nomcp");
        return $query->getResult();
    }

}
