<?php

namespace TestBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByproduit($nom)
    {
        $query=$this->getEntityManager()->createQuery("select p from TestBundle:Promotion p WHERE p.idpr=(select pr from TestBundle:Produit pr WHERE pr.nomp='$nom') ");
        return $query->getResult();
    }

}
