<?php

namespace TestBundle\Repository;

/**
 * avis_conseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheRepository extends \Doctrine\ORM\EntityRepository
{
    public function RechercheCategorieDql($categorie){

        $query=$this->getEntityManager()
            ->createQuery("Select a From TestBundle:Article a
                Where a.categorie Like :categorie ")
            ->setParameter('categorie','%'.$categorie.'%');
        return $query->getResult();

    }


}
