<?php

namespace PiBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getbyArticle($idart)
    {
        $query=$this->getEntityManager()->createQuery(
            "Select count(c) From TestBundle:Reclamation c where c.idart=:idart")->setParameter("idart",$idart);
        return $query->getResult();
    }
    public function getbyRecUser($idart,$idUser)
    {
        $query=$this->getEntityManager()->createQuery(
            "Select c From TestBundle:Reclamation c where c.idart=:idart and c.idUser=:idUser")
            ->setParameters(array(
                "idart"=>$idart,
                "idUser"=>$idUser
            ));
        return $query->getResult();
    }
}
