<?php

namespace TestBundle\Repository;
use Doctrine\ORM\Mapping\Entity;


/**
 * UserRepository
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopRepository extends \Doctrine\ORM\EntityRepository
{

    public function updateEtat($date)
    {
        $query = $this->getEntityManager()->createQuery("update TestBundle:Workshop e set e.etatws =-1 where e.datews<'$date'");
        $query->execute();
    }

    public function WorkshopsArchiver()
    {
        $query=$this->getEntityManager()->createQuery("select e from TestBundle:Workshop e WHERE e.etatws=-1 ");
        return $query->getResult();
    }

}
