forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /ecoforum

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


