<?php

namespace AdminBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function approuvereEtat($id)
    {
        $query = $this->getEntityManager()->createQuery("update TestBundle:Evenement e set e.etatev =1 where e.idev='$id'");
        $query->execute();
    }

}
