<?php

namespace AdminBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function produitEnPromoParCtagorie($id,$pourcentage)
    {
        $query = $this->getEntityManager()->createQuery("update AdminBundle:Produit p set p.enpromo =p.prix-(p.prix*('$pourcentage'/100)) where p.idcp='$id'");
        $query->execute();
    }


    public function produitNonPromoParCategorie($id)
    {
        $query = $this->getEntityManager()->createQuery("update AdminBundle:Produit p set p.enpromo =NULL where p.idcp='$id'");
        $query->execute();
    }
}
