<?php

namespace AdminBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function NombreDesPromotions()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(p)')
            ->from('AdminBundle:Promotion', 'p');

        return $queryBuilder->getQuery()->getSingleScalarResult();
    }

    public function NombreDesPromos_0_25()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(p)')
            ->from('AdminBundle:Promotion', 'p')->where('p.pourcentage>=0 AND p.pourcentage<=25');

        return $queryBuilder->getQuery()->getSingleScalarResult();
    }



    public function NombreDesPromos_25_50()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(p)')
            ->from('AdminBundle:Promotion', 'p')->where('p.pourcentage>=25 AND p.pourcentage<=50');

        return $queryBuilder->getQuery()->getSingleScalarResult();
    }




    public function NombreDesPromos_50_75()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(p)')
            ->from('AdminBundle:Promotion', 'p')->where('p.pourcentage>=50 AND p.pourcentage<=75');

        return $queryBuilder->getQuery()->getSingleScalarResult();
    }




    public function NombreDesPromos_75_100()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(p)')
            ->from('AdminBundle:Promotion', 'p')->where('p.pourcentage>=75 AND p.pourcentage<=100');

        return $queryBuilder->getQuery()->getSingleScalarResult();
    }


    public function findBycategorie($nom)
    {
        $query=$this->getEntityManager()->createQuery("select p from AdminBundle:Promotion p WHERE p.idcp=(select c from AdminBundle:Categorieprod c WHERE c.nomcp='$nom') ");
        return $query->getResult();
    }

}
